#!/usr/bin/env bash

# Define the number of times to display "Best School"
num_times=10

# Loop through the range of 1 to 10 and display "Best School"
for i in {1..$num_times}
do
    echo "Best School"
done
